# Generated by Django 3.2.5 on 2021-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
